final Map<String, List<String>> ingredientsOptions = {
  'No Gluten': [
    'Rice',
    'Quinoa',
    'Corn',
    'Potato',
    'Almond Flour',
    'Coconut Flour',
    'Sorghum',
    'Millet',
    'Buckwheat',
    'Teff',
    'Arrowroot',
    'Tapioca',
    'Amaranth'
  ],
  'No Sugar': [
    'Stevia',
    'Monk Fruit',
    'Erythritol',
    'Coconut Sugar',
    'Agave Nectar',
    'Maple Syrup',
    'Xylitol',
    'Yacon Syrup',
    'Date Sugar',
    'Brown Rice Syrup',
    'Lucuma Powder',
    'Blackstrap Molasses'
  ],
  'Dessert': [
    'Chocolate',
    'Vanilla',
    'Sugar',
    'Butter',
    'Flour',
    'Eggs',
    'Cream',
    'Baking Powder',
    'Baking Soda',
    'Cocoa Powder',
    'Brown Sugar',
    'Honey',
    'Condensed Milk',
    'Cream Cheese'
  ],
  'Healthy': [
    'Avocado',
    'Spinach',
    'Kale',
    'Berries',
    'Nuts',
    'Seeds',
    'Sweet Potato',
    'Broccoli',
    'Chia Seeds',
    'Quinoa',
    'Oats',
    'Salmon',
    'Green Tea',
    'Greek Yogurt',
    'Lentils'
  ],
  'Vegan': [
    'Tofu',
    'Tempeh',
    'Beans',
    'Lentils',
    'Nuts',
    'Seeds',
    'Seitan',
    'Nutritional Yeast',
    'Almond Milk',
    'Soy Milk',
    'Cashew Cheese',
    'Jackfruit',
    'Chickpeas',
    'Quinoa'
  ],
  'Keto': [
    'Avocado',
    'Cheese',
    'Eggs',
    'Meat',
    'Butter',
    'Olive Oil',
    'Coconut Oil',
    'Heavy Cream',
    'Spinach',
    'Zucchini',
    'Cauliflower',
    'Pork Rinds',
    'Cream Cheese',
    'Bacon'
  ],
  'Paleo': [
    'Meat',
    'Fish',
    'Fruit',
    'Vegetables',
    'Nuts',
    'Seeds',
    'Eggs',
    'Sweet Potato',
    'Coconut Oil',
    'Olive Oil',
    'Avocado Oil',
    'Honey',
    'Maple Syrup',
    'Coconut Milk'
  ],
  'Vegetarian': [
    'Cheese',
    'Eggs',
    'Milk',
    'Tofu',
    'Tempeh',
    'Legumes',
    'Greek Yogurt',
    'Vegetables',
    'Fruit',
    'Nuts',
    'Seeds',
    'Whole Grains',
    'Quinoa',
    'Chickpeas'
  ],
  'Low Carb': [
    'Eggs',
    'Meat',
    'Fish',
    'Cheese',
    'Leafy Greens',
    'Olive Oil',
    'Avocado',
    'Cauliflower',
    'Zucchini',
    'Coconut Oil',
    'Bell Peppers',
    'Broccoli',
    'Green Beans'
  ],
  'High Protein': [
    'Chicken',
    'Beef',
    'Fish',
    'Eggs',
    'Greek Yogurt',
    'Lentils',
    'Quinoa',
    'Chickpeas',
    'Cottage Cheese',
    'Almonds',
    'Tuna',
    'Turkey',
    'Peanuts',
    'Black Beans'
  ],
  'Dairy Free': [
    'Almond Milk',
    'Coconut Milk',
    'Soy Milk',
    'Tofu',
    'Nuts',
    'Seeds',
    'Coconut Oil',
    'Olive Oil',
    'Avocado',
    'Oat Milk',
    'Cashew Milk',
    'Rice Milk',
    'Coconut Yogurt'
  ],
  'Nut Free': [
    'Rice',
    'Quinoa',
    'Oats',
    'Fruit',
    'Vegetables',
    'Sunflower Seeds',
    'Pumpkin Seeds',
    'Chia Seeds',
    'Flax Seeds',
    'Coconut',
    'Coconut Flour',
    'Hemp Seeds'
  ],
  'Low Fat': [
    'Chicken Breast',
    'Turkey Breast',
    'Fish',
    'Egg Whites',
    'Beans',
    'Lentils',
    'Low-fat Yogurt',
    'Cottage Cheese',
    'Leafy Greens',
    'Bell Peppers',
    'Broccoli',
    'Cauliflower',
    'Berries',
    'Oats'
  ],
  'High Fiber': [
    'Chia Seeds',
    'Flax Seeds',
    'Lentils',
    'Black Beans',
    'Broccoli',
    'Brussels Sprouts',
    'Avocado',
    'Pears',
    'Apples',
    'Quinoa',
    'Oats',
    'Almonds',
    'Sweet Potato',
    'Berries'
  ],
  'Low Sodium': [
    'Fresh Fruits',
    'Fresh Vegetables',
    'Unsalted Nuts',
    'Seeds',
    'Dried Beans',
    'Peas',
    'Whole Grains',
    'Brown Rice',
    'Quinoa',
    'Herbs',
    'Spices',
    'Olive Oil',
    'Avocado',
    'Fresh Fish'
  ],
  'Low Cholesterol': [
    'Oats',
    'Barley',
    'Beans',
    'Eggplant',
    'Okra',
    'Nuts',
    'Vegetable Oil',
    'Apples',
    'Grapes',
    'Strawberries',
    'Citrus Fruits',
    'Soy',
    'Fatty Fish',
    'Fiber-rich Foods'
  ],
  'Heart Healthy': [
    'Salmon',
    'Mackerel',
    'Sardines',
    'Walnuts',
    'Flax Seeds',
    'Chia Seeds',
    'Oats',
    'Barley',
    'Beans',
    'Lentils',
    'Almonds',
    'Berries',
    'Dark Chocolate',
    'Leafy Greens'
  ],
  'Diabetic Friendly': [
    'Leafy Greens',
    'Cinnamon',
    'Fatty Fish',
    'Chia Seeds',
    'Turmeric',
    'Greek Yogurt',
    'Nuts',
    'Broccoli',
    'Flax Seeds',
    'Strawberries',
    'Garlic',
    'Pumpkin Seeds',
    'Dark Chocolate'
  ],
  'Anti-Inflammatory': [
    'Tomatoes',
    'Olive Oil',
    'Green Leafy Vegetables',
    'Nuts',
    'Fatty Fish',
    'Berries',
    'Oranges',
    'Cherries',
    'Turmeric',
    'Ginger',
    'Garlic',
    'Cinnamon',
    'Green Tea'
  ],
  'Immune Boosting': [
    'Citrus Fruits',
    'Red Bell Peppers',
    'Broccoli',
    'Garlic',
    'Ginger',
    'Spinach',
    'Yogurt',
    'Almonds',
    'Sunflower Seeds',
    'Turmeric',
    'Green Tea',
    'Papaya',
    'Kiwi'
  ],
  'Brain Health': [
    'Fatty Fish',
    'Blueberries',
    'Turmeric',
    'Broccoli',
    'Pumpkin Seeds',
    'Dark Chocolate',
    'Nuts',
    'Oranges',
    'Eggs',
    'Green Tea',
    'Spinach',
    'Kale',
    'Avocado',
    'Whole Grains'
  ],
};
